/**
 * Generates assets/data/demo-class.js.
 *
 * The demo is shipped as raw array-of-arrays on purpose: it travels through the
 * exact same validation pipeline as a real upload, so a judge can see the
 * import health report working without hunting for a spreadsheet.
 *
 * Two rows carry deliberate imperfections (a fractional mark and a "82/100"
 * fraction) so the health report has something honest to report, and neither
 * of them costs a student their grade.
 */
'use strict';

const path = require('path');
const fs = require('fs');

function makeRng(seed) {
  let s = seed >>> 0;
  return () => {
    s = (s * 1664525 + 1013904223) >>> 0;
    return s / 0x100000000;
  };
}

const rng = makeRng(20260926);
const clamp = (v) => Math.max(0, Math.min(100, Math.round(v)));
const id = (n) => '2024CS' + String(n).padStart(4, '0');

/** Approximate normal via the sum of three uniforms; no external libraries. */
function bell(mean, sd) {
  return clamp(mean + (rng() + rng() + rng() - 1.5) * sd * 1.15);
}

const rows = [['BITS ID', 'Course', 'Total Marks']];

const COURSES = [
  { code: 'CS101', n: 34, mean: 63, sd: 15 },
  { code: 'CS201', n: 27, mean: 76, sd: 12 },
  { code: 'EC305', n: 29, mean: 42, sd: 11, skew: true },
  { code: 'MA210', n: 9, mean: 55, sd: 4 }
];

let n = 1000;
COURSES.forEach((c) => {
  for (let i = 0; i < c.n; i++) {
    let m = c.skew ? Math.round(c.mean * (0.45 + rng() * 0.8)) : bell(c.mean, c.sd);
    m = clamp(m);
    // A little realism: a couple of perfect scores and a couple of near-zero.
    if (i === 7 && !c.skew) m = 100;
    if (i === 19 && c.skew) m = 97;
    if (i === 24) m = Math.max(m - 30, 1);
    rows.push([id(n++), c.code, m]);
  }
});

// Two honest imperfections, both of which are *recovered* and reported.
rows[9][2] = 82.6; // fractional -> rounded to 83, reported
rows[41][2] = '76/100'; // fraction form -> read as 76, reported

const body = JSON.stringify(rows, null, 0)
  .replace(/\],\[/g, '],\n  [')
  .replace(/^\[/, '[\n  ')
  .replace(/\]$/, '\n]');

const out = `/**
 * DEMO DATA - not real student records.
 *
 * Four synthetic courses with different shapes (a normal class, a strong class,
 * a weak class with one high outlier, and a small tight class) so the
 * distribution chart, statistics and band editor all have something honest to
 * show. Two rows carry recoverable imperfections on purpose.
 *
 * Generated by tools/build-demo.js. Regenerate with: node tools/build-demo.js
 */
(function (root) {
  "use strict";
  var CF = (root.CF = root.CF || {});

  CF.demoClass = {
    fileName: "demo-class.xlsx",
    sheetName: "Marks",
    meta: { demo: true, sizeBytes: 18422 },
    rows: ${body}
  };
})(typeof globalThis !== "undefined" ? globalThis : this);
`;

const dest = path.join(__dirname, '..', 'assets', 'data', 'demo-class.js');
fs.mkdirSync(path.dirname(dest), { recursive: true });
fs.writeFileSync(dest, out, 'utf8');
console.log(
  'Wrote ' + path.relative(process.cwd(), dest) + ' - ' +
  (rows.length - 1) + ' demo students across ' + COURSES.length + ' courses'
);
